spring.application.name=pulsepass

spring.datasource.url=${PULSEPASS_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pulsepass}
spring.datasource.username=${PULSEPASS_DATASOURCE_USERNAME:pulsepass}
spring.datasource.password=${PULSEPASS_DATASOURCE_PASSWORD:pulsepass}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
